#!/usr/bin/env bash

print_size_folder() {
  find "${1:-.}" -type f -ls | awk '{print $7, "\t", $11}' | sort -s -n -k 1,1 -r |  numfmt --field 1 --to=iec-i --suffix=B --format="%9.2f"
}

print_size_folder "$@"
