#!/usr/bin/env bash
info () {
    printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
    printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
    printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
    printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
    echo ''
    exit
}

info "Installing prerequisites for apacman..."
sudo pacman -S base-devel fakeroot jshon expac git && success "Done"

# Make sure our shiny new arch is up-to-date
info "Checking for system updates..."
sudo pacman -Syu

# Create a tmp-working-dir an navigate into it
mkdir -p /tmp/pacaur_install
cd /tmp/pacaur_install

# If you didn't install the "base-devil" group,
# we'll need those.
info "Installing some needed packages"
sudo pacman -S binutils make gcc fakeroot --noconfirm && success "Done"

# Install pacaur dependencies from arch repos
info "Installing prerequisites for pacaur"
sudo pacman -S expac yajl git --noconfirm && success "Done"

# Install "cower" from AUR
info "Installing cower"
curl -o PKGBUILD https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=cower
makepkg PKGBUILD --skippgpcheck
sudo pacman -U cower*.tar.xz --noconfirm && success "Done"

# Install "pacaur" from AUR
info "Installing pacaur"
curl -o PKGBUILD https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=pacaur
makepkg PKGBUILD
sudo pacman -U pacaur*.tar.xz --noconfirm && success "Done"

# Clean up...
cd ~
rm -r /tmp/pacaur_install

info "Installing terminal packages..."
pacaur --noconfirm --noedit -S \
  rxvt-unicode-256xresources \
  zsh &> /dev/null && \
  success "Installed terminal packages"

info "Installing Python dependencies..."
pacaur --noconfirm --noedit -S \
  python-basiciw \
  python-netifaces \
  python-yaml \
  python-pillow \
  python-urllib3 \
  python2-suds &> /dev/null && \
  success "Installed python dependencies"

info "Installing window manager..."
pacaur --noconfirm --noedit -S \
  xcb-util-keysyms \
  xcb-util-wm \
  xcb-util-cursor \
  yajl \
  startup-notification \
  libev \
  i3-gaps \
  i3lock \
  xedgewarp-git \
  unclutter-xfixes-git \
  i3blocks-gaps-git &> /dev/null && \
  success "WM installed"

info "Installing tools..."
pacaur --noconfirm --noedit -S \
  thunar \
  feh \
  acpi \
  compton \
  xdotool \
  pulseaudio-ctl \
  pavucontrol \
  network-manager-applet \
  networkmanager-openvpn \
  imagemagick \
  dunst \
  python \
  python-pip \
  python2-pip \
  compton-git \
  ttf-font-awesome \
  ohsnap \
  ttf-hack \
  powerline-fonts-git \
  thunar \
  weechat \
  thunar-archive-plugin \
  file-roller \
  tumbler \
  eog \
  tk \
  spotify \
  evince \
  rofi \
  libmtp \
  gvfs-mtp \
  xtitle-git \
  openssh \
  arandr \
  xclip \
  youtube-dl \
  slop \
  maim \
  neofetch-git \
  w3m \
  htop \
  bluez \
  bluez-utils \
  pulseaudio-bluetooth \
  blueman \
  redshift \
  firefox \
  lm_sensors \
  atool \
  bzip2 \
  cpio \
  gzip \
  lha \
  lzop \
  p7zip \
  tar \
  unace \
  unrar \
  unzip \
  xz \
  zip \
  vim \
  tmux \
  i3lock-fancy-git &> /dev/null && \
  success "Tools installed"

info "Installing some python stuff..."
pacaur --noconfirm --noedit -S \
  python-pillow \
  python-urllib3 &> /dev/null && \
  success "Done"

info "Installing some perl stuff..."
pacaur --noconfirm --noedit -S \
  perl-anyevent-i3 \
  perl-json-xs &> /dev/null && \
  success "Done"

success "Done installing packages"
