#!/usr/bin/env bash

# Install command-line tools using Homebrew.

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function brew-alloptions () {
    brew install "$1 $(brew options "$1" | grep -E '^--with-' - | tr '\n' ' ')"
}

# Ask for the administrator password upfront.
sudo -v

info () {
    printf "\r  [ \033[00;34m..\033[0m ] %s\n" "$1"
}

user () {
    printf "\r  [ \033[0;33m??\033[0m ] %s\n" "$1"
}

success () {
    printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
}

fail () {
    printf "\r\033[2K  [\033[0;31mFAIL\033[0m] %s\n" "$1"
    echo ''
    exit
}
# Keep-alive: update existing `sudo` time stamp until the script has finished.
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Checking if Homebrew is installed
if ! type -p brew > /dev/null ; then
    # Install Homebrew
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Update and upgrade homebrew.
#brew update
#brew upgrade --all

cd "$CURRENT_DIR" || exit 1

brew install mas

# Install ALL packages
info "Installing packages"
brew bundle

info "Installing python packages"
pip3 install neovim\
    jedi \
    mistune \
    psutil \
    setproctitle

pip2 install neovim
# Linking gsha256sum to sha256sum
sudo ln -s /usr/local/bin/gsha256sum /usr/local/bin/sha256sum

# Remove outdated versions from the cellar.
brew cleanup

cd - || exit 1