#! /bin/bash
# Ask for the administrator password upfront.
sudo -v

# Keep-alive: update existing `sudo` time stamp until the script has finished.
while true; do
	sudo -n true
	sleep 60
	kill -0 "$$" || exit
done 2>/dev/null &

if [ ! -d "$HOME/Library/QuickLook" ]; then
	mkdir -p "$HOME/Library/QuickLook"
fi
echo Installing Quick Look-plugins from Homebrew

# Checking if Homebrew is installed
if ! type -p brew >/dev/null; then
	# Install Homebrew
	ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# All Quick Look-plugins from homebrew
brew install --cask betterzipql
brew install --cask provisionql
brew install --cask invisorql
brew install --cask qlcolorcode
brew install --cask qlimagesize
brew install --cask qlmarkdown
brew install --cask qlprettypatch
brew install --cask quicklook-csv
brew install --cask quicklook-json
brew install --cask quicknfo scriptql
brew install --cask suspicious-package
brew install --cask webpquicklook

# All Quick Look-plugins that aren't in homebrew
echo Installing/Downloading Quick Look-plugins that are not from Homebrew
echo THEY MIGHT BE OUTDATED
# Failsafe if cd doesn't work
cd "$HOME/Library/QuickLook/" || exit 1

curl -fSsL https://github.com/whomwah/qlstephen/releases/download/1.4.4/QLStephen.qlgenerator.1.4.4.zip -o QLStephen.zip

# Moving into QuickLook-folder to extract the .zip's
for filename in ./*.zip; do
	unzip -q "$filename"
done

# Removing all .zip-archives
rm -rf ./*.zip
echo Restarting Quick Look-manager
qlmanage -r
