#!/usr/bin/env bash

case "$1" in
    lock)
        $HOME/.i3/i3-lock "$HOME/Pictures/arch-logo-mini.png"
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        $HOME/.i3/i3-suspend
        ;;
    hibernate)
        systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 [lock|logout|suspend|hibernate|reboot|shutdown]"
        exit 2
esac

exit 0
