#!/bin/zsh
#
# Bspwm configuration
#
# =====================
# Initialition
# =====================

bash ${HOME}/.xinitrc
sxhkd &
compton -b &
(sleep 5; ${HOME}/.config/polybar/launch.sh) &
bash "${HOME}/.wallpapers/wp_init.sh" &
trayer --edge bottom --align left --margin 5 --transparent true --alpha 255 --iconspacing 5 --height 24 &
nm-applet &
blueman-applet &
dunst &
#xautolock -time 15 -locker '$HOME/.i3/i3exit lock' &

# =====================
# Config
# =====================

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_border_color "$color1"

bspc config border_width        3
bspc config window_gap          25
bspc config top_padding         25

bspc config split_ratio          0.5

bspc config paddingless_monocle     true
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config click_to_focus          true
bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true

if [ "$(hostname)" = "archbox" ];
then
    bspc monitor "$(bspc wm -d | jq ".monitors[] | select(.name == \"DP-5\").id")" -d I II III
    bspc monitor "$(bspc wm -d | jq ".monitors[] | select(.name == \"DP-2.8\").id")" -d IV V VI VII
    bspc monitor "$(bspc wm -d | jq ".monitors[] | select(.name == \"HDMI-0\").id")" -d VIII IX X
else
    bspc monitor -d 1 2 3 4 5 6
fi

bspc wm --adopt-orphans
