#!/usr/bin/env bash
source "./outputs.sh"

set -e

info "Installing prerequisites for apacman..."
sudo pacman -S base-devel fakeroot jshon expac git &> /dev/null && success "Done"

info "Installing apacman..."
cd "$(mktemp -d)"
git clone https://aur.archlinux.org/apacman &> /dev/null
cd apacman
makepkg -si && success "Done"
cd -

info "Installing terminal packages..."
apacman --noconfirm --noedit -S \
  termite-git \
  zsh &> /dev/null && \
  success "Installed terminal packages"

info "Installing Python dependencies..."
apacman --noconfirm --noedit -S \
  python-basiciw \
  python-netifaces \
  python-yaml \
  python-pillow \
  python-urllib3 \
  python2-suds &> /dev/null && \
  success "Installed python dependencies"

info "Installing window manager..."
apacman --noconfirm --noedit -S \
  xcb-util-keysyms \
  xcb-util-wm \
  xcb-util-cursor \
  yajl \
  startup-notification \
  libev \
  i3-gaps \
  i3lock \
  xedgewarp-git \
  unclutter-xfixes-git \
  i3blocks-gaps-git &> /dev/null && \
  success "WM installed"

info "Installing tools..."
apacman --noconfirm --noedit -S \
  gsimplecal \
  thunar \
  feh \
  acpi \
  compton \
  xdotool \
  pulseaudio-ctl \
  pavucontrol \
  network-manager-applet \
  networkmanager-openvpn \
  imagemagick \
  dunst \
  python \
  python-pip \
  python2-pip \
  compton-git \
  ttf-font-awesome \
  ohsnap \
  ttf-hack \
  powerline-fonts-git \
  thunar \
  weechat \
  thunar-archive-plugin \
  file-roller \
  tumbler \
  eog \
  numix-themes \
  numix-icon-theme-git \
  tk \
  spotify \
  evince \
  rofi \
  libmtp \
  gvfs-mtp \
  xtitle-git \
  openssh \
  arandr \
  xclip \
  thefuck \
  youtube-dl \
  slop \
  maim \
  neofetch-git \
  w3m \
  htop \
  bluez \
  bluez-utils \
  pulseaudio-bluetooth \
  blueman \
  redshift \
  google-chrome \
  firefox \
  lm_sensors \
  atool \
  bzip2 \
  cpio \
  gzip \
  lha \
  lzop \
  p7zip \
  tar \
  unace \
  unrar \
  unzip \
  xz \
  zip \
  exa-git \
  i3lock-fancy-git &> /dev/null && \
  success "Tools installed"

info "Installing some python stuff..."
apacman --noconfirm --noedit -S \
  python-pillow \
  python-urllib3 &> /dev/null && \
  success "Done"

info "Installing some perl stuff..."
apacman --noconfirm --noedit -S \
  perl-anyevent-i3 \
  perl-json-xs &> /dev/null && \
  success "Done"

success "Done installing packages"