#!/usr/bin/env bash
set -e

source "./outputs.sh"

info "Installing terminal packages..."
sudo apt install -y \
  zsh &> /dev/null && \
  success "Installed termial packages"

#sh -c "$(curl -fsSL https://github.com/Corwind/termite-install/raw/master/termite-install.sh)"

info "Installing Python dependencies..."
sudo apt install -y \
  python \
  python3 &> /dev/null && \
  success "Done"

info "Installing window manager dependencies..."
sudo apt install -y \
  libxcb1-dev \
  libxcb-keysyms1-dev \
  libpango1.0-dev \
  libxcb-util0-dev \
  libxcb-icccm4-dev \
  libyajl-dev \
  libx11-xcb-dev \
  libstartup-notification0-dev \
  libxcb-randr0-dev \
  libev-dev \
  libxcb-cursor-dev \
  libxcb-xinerama0-dev \
  libxcb-xkb-dev \
  libxkbcommon-dev \
  libxkbcommon-x11-dev \
  help2man &> /dev/null && \
  success "WM dependencies installed"

info "Installing i3-gaps.."
cd ~

# clone the repository
cd "$(mktemp -d)"

git clone https://www.github.com/Airblader/i3 .i3-gaps &> /dev/null

cd .i3-gaps

# do this if you want the stable branch, skip it if you want the dev branch (gaps-next)
git checkout gaps && git pull &> /dev/null

# compile & install
make &> /dev/null
sudo make install &> /dev/null

cd "$(mktemp -d)"
git clone git://github.com/Airblader/i3blocks-gaps .i3blocks-gaps &> /dev/null
cd .i3blocks-gaps
make clean all &> /dev/null
sudo make install &> /dev/null
success "Installed i3-gaps"

info "Installing light"
cd "$(mktemp -d)"
git clone https://github.com/haikarainen/light .light &> /dev/null
cd .light
make &> /dev/null
sudo make install &> /dev/null

success "Light installed!"
cd ~

info "Installing tools..."
sudo apt install -y \
  i3lock \
  i3status \
  gsimplecal \
  thunar \
  curl \
  cmake \
  openssl \
  libssl-dev \
  vim \
  feh \
  acpi \
  compton \
  xdotool \
  pulseaudio \
  pavucontrol \
  imagemagick \
  dunst \
  fonts-font-awesome \
  fonts-hack-ttf \
  fonts-powerline \
  weechat \
  thunar-archive-plugin \
  file-roller \
  tumbler \
  eog \
  numix-gtk-theme \
  tk \
  evince \
  rofi \
  libmtp9 \
  xtitle \
  ssh \
  arandr \
  xclip \
  thefuck \
  youtube-dl \
  w3m \
  htop \
  bluez \
  bluez-tools \
  pulseaudio-module-bluetooth \
  blueman \
  redshift \
  redshift-gtk \
  firefox \
  lm-sensors \
  atool \
  bzip2 \
  cpio \
  gzip \
  lzop \
  p7zip \
  tar \
  unrar \
  unzip \
  zip &> /dev/null && \
  success "Tools installed"


info "Installing rust"
if ! type -p rustc > /dev/null ; then
  curl -sSf https://static.rust-lang.org/rustup.sh | sh &> /dev/null && success "Rust inslled"
fi
info "Installing exa"
cd "$(mktemp -d)"
git clone https://github.com/ogham/exa .exa &> /dev/null
cd .exa
sudo make install &> /dev/null && \
success "Done!"
