#!/usr/bin/env bash
# This way you can customize which branches should be skipped when
# prepending commit message.
MESSAGE=$(<"$1")
TICKET=$(git rev-parse --abbrev-ref HEAD | grep -Eoi '[a-z]{2,4}-[0-9]+' | tr "[:lower:]" "[:upper:]")
COMMIT_SOURCE=$2

if [ "$COMMIT_SOURCE" == "merge" ]; then
	exit 0
fi

if [ -z "$TICKET" ]; then
	echo "Not on a feature branch. Skipping commit-prepending"
	exit 0
fi

if [[ "$MESSAGE" == "$TICKET"* ]]; then
	echo "Ticket found in commit message. Skipping..."
	exit 0
fi

echo "$TICKET/1/1: $MESSAGE" >"$1"
