#!/usr/bin/env bash
info () {
    printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}
info 'start updating ...'

if type brew >/dev/null; then
    info 'updating homebrew'
    brew update
    brew upgrade
    brew cleanup
elif type apacman >/dev/null; then
    info 'updating pacman'
    apacman -Syu
fi

case "$SHELL" in
*/fish)
    info 'updating fish shell'
    fish -c fisher up
    fish -c fish_update_completions
    ;;
*/zsh)
    info 'updating zsh shell'
    zsh -c zplug update
    ;;
esac

if type softwareupdate >/dev/null; then
    info 'checking Apple Updates'
    /usr/sbin/softwareupdate -ia
fi

exit 0
